-- Supabase schema for GrooveFlow
-- Run this in Supabase SQL Editor

-- Users profile extension
create table if not exists public.profiles (
  id uuid references auth.users on delete cascade primary key,
  email text,
  name text,
  avatar_url text,
  role text default 'user',
  is_verified boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Tracks
create table if not exists public.tracks (
  id bigint generated by default as identity primary key,
  title text not null,
  artist text not null,
  album text,
  genre text,
  mood text,
  cover_url text,
  url text,
  is_podcast boolean default false,
  duration int default 0,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Playlists
create table if not exists public.playlists (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  name text not null,
  track_ids bigint[] default '{}',
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Albums
create table if not exists public.albums (
  id bigint generated by default as identity primary key,
  name text not null,
  artist_id uuid references auth.users not null,
  cover_url text,
  track_ids bigint[] default '{}',
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Likes
create table if not exists public.likes (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  track_id bigint not null,
  created_at timestamp with time zone default timezone('utc'::text, now()),
  unique(user_id, track_id)
);

-- History
create table if not exists public.history (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  track_id bigint not null,
  played_at timestamp with time zone default timezone('utc'::text, now())
);

-- Notifications
create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  message text not null,
  read boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Follows
create table if not exists public.follows (
  id bigint generated by default as identity primary key,
  follower_id uuid references auth.users not null,
  following_id uuid references auth.users not null,
  created_at timestamp with time zone default timezone('utc'::text, now()),
  unique(follower_id, following_id)
);

-- Storage bucket for audio files (run after enabling storage)
-- insert into storage.buckets (id, name, public) values ('audio', 'audio', true);

-- RLS policies
alter table public.profiles enable row level security;
alter table public.tracks enable row level security;
alter table public.playlists enable row level security;
alter table public.albums enable row level security;
alter table public.likes enable row level security;
alter table public.history enable row level security;
alter table public.notifications enable row level security;
alter table public.follows enable row level security;

-- Profiles: read public, write own
create policy "Public profiles are viewable by everyone" on public.profiles for select using (true);
create policy "Users can insert their own profile" on public.profiles for insert with check (auth.uid() = id);
create policy "Users can update own profile" on public.profiles for update using (auth.uid() = id);

-- Tracks: read public, insert authenticated
create policy "Tracks are viewable by everyone" on public.tracks for select using (true);
create policy "Authenticated users can insert tracks" on public.tracks for insert with check (auth.role() = 'authenticated');

-- Playlists: read public, insert/update own
create policy "Playlists are viewable by everyone" on public.playlists for select using (true);
create policy "Users can insert own playlists" on public.playlists for insert with check (auth.uid() = user_id);
create policy "Users can update own playlists" on public.playlists for update using (auth.uid() = user_id);
create policy "Users can delete own playlists" on public.playlists for delete using (auth.uid() = user_id);

-- Albums: read public, insert authenticated
create policy "Albums are viewable by everyone" on public.albums for select using (true);
create policy "Authenticated users can insert albums" on public.albums for insert with check (auth.role() = 'authenticated');

-- Likes: read own, insert/delete own
create policy "Users can view own likes" on public.likes for select using (auth.uid() = user_id);
create policy "Users can insert own likes" on public.likes for insert with check (auth.uid() = user_id);
create policy "Users can delete own likes" on public.likes for delete using (auth.uid() = user_id);

-- History: read own, insert own
create policy "Users can view own history" on public.history for select using (auth.uid() = user_id);
create policy "Users can insert own history" on public.history for insert with check (auth.uid() = user_id);

-- Notifications: read own, insert any
create policy "Users can view own notifications" on public.notifications for select using (auth.uid() = user_id);
create policy "Users can update own notifications" on public.notifications for update using (auth.uid() = user_id);

-- Follows: read public, insert authenticated
create policy "Follows are viewable by everyone" on public.follows for select using (true);
create policy "Authenticated users can follow" on public.follows for insert with check (auth.role() = 'authenticated');
create policy "Users can unfollow own follows" on public.follows for delete using (auth.uid() = follower_id);
